# Indicamos la versión
# Para iniciar docker-compose up -d
version: '3.7'

# Mis servicios
# Iniciamos los servicios
services:
  # MARIA DB
  mariadb:
    build: ./mariadb
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - dbvolume:/var/lib/mysql
    networks:
      - dbnetwork
    # restart: always

  # ADMIN MARIADB
  adminer:
    image: adminer
    container_name: adminer
    # restart: always
    ports:
      - 8080:8080
    networks:
      - dbnetwork
    depends_on:
      - mariadb

# Mi volumenes de datos compartidos
volumes:
  dbvolume:

# Si queremos que tengan una red propia a otros contenedores
networks:
  dbnetwork:
    driver: bridge